### ISSUE TITLE
Theme request for hyperterm

### ISSUE THREAD

**Issue by ciscohack** [ulwlu/elly-iterm2#3]
Hello Expert,

Can you please create this theme for hyper terminal also. i love this theme

**Comment by ulwlu** [comment]
Hi. I'm happy if you love this. Thanks.

I'll look at it until this week.

**Comment by ciscohack** [comment]
Sure thanks

**Comment by ulwlu** [comment]
@ciscohack 

hey, i created it here.

```javascript
const colors = {
  black:        "#111A1F",
  red:          "#8D7856",
  green:        "#798362",
  yellow:       "#9B9257",
  blue:         "#63768A",
  magenta:      "#738C9C",
  cyan:         "#6998B3",
  white:        "#9A9A9A",
  lightBlack:   "#868b8d",
  lightRed:     "#8D7856",
  lightGreen:   "#798362",
  lightYellow:  "#9B9257",
  lightBlue:    "#63768A",
  lightMagenta: "#738C9C",
  lightCyan:    "#6998B3",
  lightWhite:   "#9A9A9A",
};

const originalColors = {
  gray1: "#161f2a"
};

const cursorColor = colors.yellow;
const foregroundColor = colors.white;
const backgroundColor = colors.black;
const selectionColor = originalColors.gray1;
const borderColor = originalColors.gray1;

exports.decorateConfig = (config) =>
  Object.assign({}, config, {
    cursorColor,
    foregroundColor,
    backgroundColor,
    selectionColor,
    borderColor,
    colors,
    css: config.css || '',
    termCSS: config.termCSS || ''
  });
```

but, before publishing I have a suggestion. Don't you want to have this `hyper-elly` repository by yourself?

I don't think I will use hyper in future, so I have less opportunities to improve. It won't be good to hyper community.

But if you are the one want to use this and have this repository by yourself, you can improve by your own decision, it will be better.

**Comment by ciscohack** [comment]
@ulwlu Thanks for quick help on this. I am travelling for month.. will check and keep repo and maintain for my taste if need but you theme hardly need any change. you can release it  and thanks for your effort. btw you only created index.js.. we don't need package.json file?

**Comment by ulwlu** [comment]
Ok i'm gonna release. I will tell you later.

If you are ready after traveling, please let me know. I will transfer the ownership of repository and npmjs.

yes i have package.json in local as well, it's almost empty, though.

**Comment by ciscohack** [comment]
you can transfer repro now.. i have seen the screenshot and i am using your theme in iterm2. so its looks same and working.. if any change needed i will do else not need to change in it

**Comment by ciscohack** [comment]
@ulwlu I have one question you use window manager on your macOS. is it really better than what we have natively

**Comment by ulwlu** [comment]
@ciscohack ok. Now I send you transfer request. You will see the email from github.

Yes. It's much better to me. I use rectangle which can manage the window into half in any direction, so that i can easily do multiple tasks. I used to use yabai as well, it's  also great.

**Comment by ciscohack** [comment]
Thanks once again my friend. is these windows manager stable ... i will check some youtube video about these tools. Thanks have a nice day

**Comment by ciscohack** [comment]
it's your work and your theme ..always whoever will install this great theme should know who created .. i never ever change the name. Thanks

**Comment by ciscohack** [comment]
@ulwlu One last help could you please do on this .. I asked one of my friend to test it and he saying he is getting follow error "an unexpected error occurred https //registry.yarnpkg.com/ package not found"

seems yarn/npm we need to register it.. i really have not much idea of it and second don't have system to do research  if you could just fix this also would be big help ..Later i will handle once back.

**Comment by ulwlu** [comment]
Well it's easy. Just follow the blow link and publosh package to npmjs.

https://zellwk.com/blog/publish-to-npm/

**Comment by ciscohack** [comment]
@ulwlu Yes my friend i checked this link on mobile but can't do as not have system so i requested. if you could just publish it

**Comment by ulwlu** [comment]
please do it when you can. it's troublesome to transfer npm ownership so not my motivation.

at least you can put hyper elly in localPlugins in hyper.js

**Comment by ciscohack** [comment]
Sure thanks no problem
